teleop_twist_joy:
  ros__parameters:
    enable_button: 4  # L1 to enable motion
    axis_linear.x: 1  # left stick vertical
    axis_linear.y: 0  # left stick horizontal
    axis_angular.yaw: 2  # right stick horizontal

    scale_linear.x: 1.0
    scale_linear.y: 1.0
    scale_angular.yaw: 1.0

    enable_turbo_button: 5  # R1 (optional for turbo mode)
    scale_linear_turbo.x: 2.0
    scale_angular_turbo.yaw: 2.0
